url: "https://fu.sd.tmu.ac.jp"
theme: jekyll-theme-primer
plugins:
 - jekyll-sitemap

title: Fukuchi, Yosuke
google_analytics: G-DGMQFP7CTR
defaults:
    -
      scope:
        path: ""
      values:
        layout: "default"
    -
      scope:
        path: "files/*"
      values:
        sitemap: false
    -
      scope:
        path: "google875788e81f7017a0.html"
      values:
        sitemap: false
